import 'package:flutter/material.dart';
import 'package:platform_design/ui/theme/color/color_resource.dart';
import 'package:platform_design/ui/theme/typography/font_resource.dart';

// TODO:
//  어차피 바뀔 것이기 때문에 테스트 데이터 상태. 디자인 가이드 나오면 변경할 것.
//  const 유지 하는게 좋음.
TextTheme KTTextTheme = const TextTheme(
  displayLarge: TextStyle(
    fontWeight: FontWeight.normal,
    fontSize: 57,
    height: 1.2,
    letterSpacing: -0.25,
    color: KTColorResource.appBlack,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  displayMedium: TextStyle(
    fontWeight: FontWeight.normal,
    fontSize: 45,
    height: 1.2,
    letterSpacing: -0.25,
    color: KTColorResource.appBlack,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  displaySmall: TextStyle(
    fontWeight: FontWeight.normal,
    fontSize: 36,
    height: 1.2,
    letterSpacing: -0.25,
    color: KTColorResource.appBlack,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  headlineLarge: TextStyle(
    fontWeight: FontWeight.normal,
    fontSize: 32,
    height: 1.2,
    letterSpacing: -0.25,
    color: KTColorResource.appBlack,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  headlineMedium: TextStyle(
    fontWeight: FontWeight.normal,
    fontSize: 28,
    height: 1.2,
    letterSpacing: -0.25,
    color: KTColorResource.appBlack,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  headlineSmall: TextStyle(
    fontWeight: FontWeight.normal,
    fontSize: 24,
    height: 1.2,
    letterSpacing: -0.25,
    color: KTColorResource.appBlack,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  titleLarge: TextStyle(
    fontWeight: FontWeight.w500,
    fontSize: 22,
    height: 1.2,
    letterSpacing: -0.25,
    color: KTColorResource.appBlack,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  titleMedium: TextStyle(
    fontWeight: FontWeight.w500,
    fontSize: 18,
    height: 1.2,
    letterSpacing: -0.25,
    color: KTColorResource.appBlack,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  titleSmall: TextStyle(
    fontWeight: FontWeight.w500,
    fontSize: 14,
    height: 1.2,
    letterSpacing: -0.25,
    textBaseline: TextBaseline.alphabetic,
    color: KTColorResource.appBlack,
    fontFamily: KTFontResource.fontName,
  ),
  bodyLarge: TextStyle(
    fontWeight: FontWeight.normal,
    fontSize: 16,
    height: 1.2,
    letterSpacing: -0.25,
    color: KTColorResource.appBlack,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  bodyMedium: TextStyle(
    fontWeight: FontWeight.normal,
    fontSize: 14,
    height: 1.2,
    color: KTColorResource.appBlack,
    letterSpacing: -0.25,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  bodySmall: TextStyle(
    fontWeight: FontWeight.normal,
    fontSize: 12,
    height: 1.2,
    color: KTColorResource.appBlack,
    letterSpacing: -0.25,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  labelLarge: TextStyle(
    fontWeight: FontWeight.normal,
    fontSize: 16,
    height: 1.2,
    letterSpacing: -0.25,
    color: KTColorResource.appBlack,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  labelMedium: TextStyle(
    fontWeight: FontWeight.normal,
    fontSize: 16,
    height: 1.2,
    letterSpacing: -0.25,
    color: KTColorResource.appBlack,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
  labelSmall: TextStyle(
    fontWeight: FontWeight.normal,
    fontSize: 12,
    height: 1.2,
    letterSpacing: -0.25,
    color: KTColorResource.appBlack,
    textBaseline: TextBaseline.alphabetic,
    fontFamily: KTFontResource.fontName,
  ),
);